/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.74
 * Generated at: 2023-06-07 00:00:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class boardDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.1.jar", Long.valueOf(1685949239313L));
    _jspx_dependants.put("jar:file:/D:/ThisisAJAX/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ThisisAJAX/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.1.jar!/META-INF/c.tld", Long.valueOf(1323225978000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"UTF-8\">\r\n");
      out.write("	<title>Insert title here</title>\r\n");
      out.write("	<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.0/jquery.min.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		$(function(){\r\n");
      out.write("			$('#submit').click(function(){\r\n");
      out.write("				$.ajax(\r\n");
      out.write("						{\r\n");
      out.write("							url:\"insertComment\",\r\n");
      out.write("							data:{\r\n");
      out.write("								board_seq : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.board.seq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\",\r\n");
      out.write("								content : $(\"#commentTxt\").val()\r\n");
      out.write("							},\r\n");
      out.write("							type:\"POST\",\r\n");
      out.write("							success:function(data){\r\n");
      out.write("								if(data <= 0) alert(\"등록실패!\");\r\n");
      out.write("	                			else {\r\n");
      out.write("	                				alert(\"등록완료!\");\r\n");
      out.write("	                				refresh();\r\n");
      out.write("	                			}\r\n");
      out.write("							},\r\n");
      out.write("							error:function(e){\r\n");
      out.write("								console.log(e);\r\n");
      out.write("							}\r\n");
      out.write("						}\r\n");
      out.write("				);				\r\n");
      out.write("			})\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			$('#comment_table').on('click', '.delete', function(event){ //삭제버튼에 클릭이벤트추가\r\n");
      out.write("                let tr = $(this).parent().parent(); //삭제버튼이 눌러진 행 tr\r\n");
      out.write("                let boardSeq = parseInt($(tr).children().eq(0).text());\r\n");
      out.write("                let seq = parseInt($(tr).children().eq(1).text());\r\n");
      out.write("                $.ajax(\r\n");
      out.write("                	{\r\n");
      out.write("                		url:\"deleteComment\",\r\n");
      out.write("                		data:{boardSeq:boardSeq, seq:seq},\r\n");
      out.write("                		type:\"POST\",\r\n");
      out.write("                		success:function(data){\r\n");
      out.write("                			if(data <= 0) alert(\"삭제실패!\");\r\n");
      out.write("                			else {\r\n");
      out.write("                				alert(\"삭제완료!\");\r\n");
      out.write("                				refresh();\r\n");
      out.write("                			}\r\n");
      out.write("                		},\r\n");
      out.write("                		error:function(e){\r\n");
      out.write("                			console.log(e);\r\n");
      out.write("                		}\r\n");
      out.write("                		\r\n");
      out.write("                	}\r\n");
      out.write("                );                \r\n");
      out.write("				\r\n");
      out.write("            });\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			$('#comment_table').on('click', '.update', function(event){ //삭제버튼에 클릭이벤트추가\r\n");
      out.write("                let tr = $(this).parent().parent(); //삭제버튼이 눌러진 행 tr\r\n");
      out.write("                let boardSeq = parseInt($(tr).children().eq(0).text());\r\n");
      out.write("                let seq = parseInt($(tr).children().eq(1).text());\r\n");
      out.write("                let content =  $(tr).children().eq(2).children().val();\r\n");
      out.write("                $.ajax(\r\n");
      out.write("                	{\r\n");
      out.write("                		url:\"updateComment\",\r\n");
      out.write("                		data:{boardSeq:boardSeq, seq:seq , content:content},\r\n");
      out.write("                		type:\"POST\",\r\n");
      out.write("                		success:function(data){\r\n");
      out.write("                			//console.log(data);\r\n");
      out.write("                			if(data <= 0) alert(\"수정실패!\");\r\n");
      out.write("                			else {\r\n");
      out.write("                				alert(\"수정완료!\");\r\n");
      out.write("                				refresh();\r\n");
      out.write("                			}\r\n");
      out.write("                		},\r\n");
      out.write("                		error:function(e){\r\n");
      out.write("                			console.log(e);\r\n");
      out.write("                		}\r\n");
      out.write("                		\r\n");
      out.write("                	}\r\n");
      out.write("                );        \r\n");
      out.write("				\r\n");
      out.write("            });\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			function refresh() {\r\n");
      out.write("				$('#comment_table').empty();\r\n");
      out.write("			    $.ajax({\r\n");
      out.write("			        url: \"refresh\",\r\n");
      out.write("			        data: { board_seq: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.board.seq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" },\r\n");
      out.write("			        dataType: \"json\",\r\n");
      out.write("			        success: function(data) {\r\n");
      out.write("			            $.each(data, function(index, item) {\r\n");
      out.write("			                $('#comment_table').append(\r\n");
      out.write("			                    \"<tr><td>\" + item.boardSeq + \"</td>\" +\r\n");
      out.write("			                    \"<td>\" + item.seq + \"</td>\" +\r\n");
      out.write("			                    '<td><input type=\"text\" class=\"form-control\" id=\"content\" name=\"content\" value=\"' + item.content + '\"></td>' +\r\n");
      out.write("			                    '<td><input type=\"button\" class=\"btn update\" value=\"수정\" onclick=\"\"></td>' +\r\n");
      out.write("			                    '<td><input type=\"button\" class=\"btn delete\" value=\"삭제\"></td></tr>'\r\n");
      out.write("			                );\r\n");
      out.write("			            });\r\n");
      out.write("			        }\r\n");
      out.write("			    });\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			refresh();\r\n");
      out.write("			\r\n");
      out.write("		});\r\n");
      out.write("	</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<form action=\"register.do\" method=\"post\">\r\n");
      out.write("	<table class=\"container table table-borderless\">\r\n");
      out.write("		<thead class=\"text-center\">\r\n");
      out.write("				<h3>상세보기</h3>\r\n");
      out.write("		</thead>\r\n");
      out.write("		<tr class=\"row\">\r\n");
      out.write("			<td class=\"col-md-4\"></td>\r\n");
      out.write("			<td class=\"col-md-4\">\r\n");
      out.write("				<div class=\"form-floating\">\r\n");
      out.write("				  <input type=\"text\" class=\"form-control\" id=\"seq\" name=\"seq\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.board.seq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required>\r\n");
      out.write("				  <label for=\"floatingInput\">seq</label>\r\n");
      out.write("				</div>\r\n");
      out.write("			</td>\r\n");
      out.write("			<td class=\"col-md-4\"></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr class=\"row\">\r\n");
      out.write("			<td class=\"col-md-4\"></td>\r\n");
      out.write("			<td class=\"col-md-4\">\r\n");
      out.write("				<div class=\"form-floating\">\r\n");
      out.write("				  <input type=\"text\" class=\"form-control\" id=\"title\" name=\"title\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.board.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required>\r\n");
      out.write("				  <label for=\"floatingInput\">title</label>\r\n");
      out.write("				</div>\r\n");
      out.write("			</td>\r\n");
      out.write("			<td class=\"col-md-4\"></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr class=\"row\">\r\n");
      out.write("			<td class=\"col-md-4\"></td>\r\n");
      out.write("			<td class=\"col-md-4\">\r\n");
      out.write("				<div class=\"form-floating\">\r\n");
      out.write("				  <input type=\"text\"class=\"form-control\" id=\"content\" name=\"content\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.board.content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("				  <label for=\"floatingInput\">content</label>\r\n");
      out.write("				</div>				\r\n");
      out.write("			</td>\r\n");
      out.write("			<td class=\"col-md-4\"></td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr class=\"row\">\r\n");
      out.write("			<td class=\"col-md-4\"></td>\r\n");
      out.write("			<td class=\"col-md-4\">\r\n");
      out.write("				<div class=\"form-floating\">\r\n");
      out.write("				  <input type=\"email\" class=\"form-control\" id=\"regdate\" name=\"regdate\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.board.regdate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("				  <label for=\"floatingInput\">regdate</label>\r\n");
      out.write("				</div>	\r\n");
      out.write("			</td>\r\n");
      out.write("			<td class=\"col-md-4\"></td>		\r\n");
      out.write("		</tr>\r\n");
      out.write("	</table>\r\n");
      out.write("</form>\r\n");
      out.write("<hr>\r\n");
      out.write("<form>\r\n");
      out.write("	<h5>댓글존</h5>\r\n");
      out.write("	<input type=\"text\" id=\"commentTxt\" name=\"commentTxt\" placeholder=\"댓글을 입력해주세용\">\r\n");
      out.write("	<input type=\"button\" id=\"submit\" value=\"댓글입력\">\r\n");
      out.write("	<table class=\"table\" id=\"comment_table\">		\r\n");
      out.write("	</table>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
